apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-python
  labels:
    app: hello-world-python
    kubernetes.azure.com/generator: devhub
  namespace: hello-world-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-python
  template:
    metadata:
      labels:
        app: hello-world-python
    spec:
      containers:
        - name: hello-world-python
          image: srinman.azurecr.io/aksghautodeploy:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
