apiVersion: v1
kind: Service
metadata:
  name: hello-world-python
  namespace: hello-world-namespace
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: hello-world-python
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000